version: '3.8'
services:
    # Application
    app:
        container_name: laravel-app
        build:
            context: .
            dockerfile: ./.docker/app.dockerfile
        depends_on:
            - "laravel-db"
        networks:
            - laravel-network
        volumes:
            - .:/var/www
    # Web Server
    web:
        container_name: laravel-web
        build:
            context: .
            dockerfile: ./.docker/web.dockerfile
        depends_on:
            - "laravel-app"
        ports:
            - 80:80
        networks:
            - laravel-network
        volumes:
            - .:/var/www
    # Database
    db:
        container_name: laravel-db
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        networks:
            - laravel-network
volumes:
    dbdata:
networks:
    laravel-network:
        driver: bridge
